### ISSUE TITLE
지출추가화면 예산추가도 대응할 수 있도록 개선

### ISSUE THREAD

**Issue by nalaworld** [boostcamp-2020/Project18-A-BoostPocket#145]
### Description
지출추가화면이 현재 지출에 대해서만 대응이 되는데 이를 예산에도 대응할 수 있도록 구현

### Todo
- [ ] 지출/수입에 따라 뷰 색깔 다르게 하기
- [ ] 카드/현금과 같은 지출/수입에 따라 보일수도있고 안보일수도 있는 뷰에 대해서 dynamic 하게 처리
- [ ] BaseData를 ViewModel 단위로 조정하기
