### ISSUE TITLE
Contry Entity에 identifier 정보 추가하기

### ISSUE THREAD

**Issue by nalaworld** [boostcamp-2020/Project18-A-BoostPocket#161]
### Description
지출목록화면이나 지출상세화면에서 보여줘야 할 currency symbol 문자열을 구하기 위해 identifier가 필요함.
Country Entity에 identifier 정보를 추가하고 해당 정보를 필요로 하는 ViewModel들의 구조도 변경할 것

### Todo
- [ ] Country Entity에 identifier 정보 추가
- [ ] 국가 생성 하는 persistenceManager의 createCountriesWithAPIRequest 부분 수정
- [ ] TravelItemViewModel (여행상세, 지출목록, 지출추가/수정, 지출상세, 리포트 화면에 사용될 데이터를 뷰로 넘겨주는 뷰모델)에도 countryIdentifier 정보 추가

### Checkpoints
- [ ] 테스트코드를 제대로 수정했는가?
- [ ] side effect를 제대로 점검했는가?
