### ISSUE TITLE
TravelProvider, ListViewModel에 여행 정보 Update 기능 구현

### ISSUE THREAD

**Issue by nalaworld** [boostcamp-2020/Project18-A-BoostPocket#83]
### Description
TravelProfileViewController에서 여행정보 변경 -> TravelListViewModel <-> TravelProvider <-> PersistenceManager 흐름 완성하기
TravelListViewModel이 업데이트 된 여행 정보를 Provider로부터 다시 받으면 TravelItemViewModel의 내부 정보를 수정
TravelItemViewModel을 class type으로 변경해서 TravelListViewModel이 갖고있는 실체화된 객체를 여행프로필/지출목록/리포트 등 TabbarController의 VC들이 weak 참조하도록 구조 변경

### Todo
- [ ] TravelProvider, TravelProviderTests에 update 기능 구현
- [ ] TravelListViewModel에 update 기능 구현
- [ ] TravelProfileViewController와 update 함수 연결
